### ISSUE TITLE
Error during Make command

### ISSUE THREAD

**Issue by joaolaureano** [samuelrsilva/pdb2stl#1]
Hello, I'm catching a error during the make command
"Makefile:23: recipe for target 'decimate' failed"
I've run the commands in the tutorial, as requested.
Even though, not getting good.
I'm running in a Ubuntu 18.04

**Comment by samuelrsilva** [comment]
Hi, thank you for pointing out!
The program needed to be updated to the current version of libigl; it should work now. Please try again.

**Comment by joaolaureano** [comment]
It worked like a charm!
Thanks
