### ISSUE TITLE
Print a non-surface style of protein

### ISSUE THREAD

**Issue by joaolaureano** [samuelrsilva/pdb2stl#2]
I'd like to do a 3D model of the protein using a style such as Cartoon, or Backbone. Is it possible ?
Attached, a file of something that is what I think it'd be awesome to do.
![1zdd_screenshot](https://user-images.githubusercontent.com/42150235/59446906-c7707880-8dd8-11e9-8505-3a7b92d47e60.png)

**Comment by laurestk** [comment]
The idea for 3D printing surfaces at first was to make it easy to reproduce structures using FDM machines, backbones and cartoons are QUITE dificult to reproduce perfectly by FDM. Ive been using photopolimerization for that and took 3D models ready from the NIH 3D printing database or something from Thingiverse, otherwise giving a try on chimera, pymol or vmd to generate the models. But I would prefer generating backbones and cartoon models using pdb2stl.

**Comment by joaolaureano** [comment]
I'd either. The idea is to use something as an API, and not use Chimera, or anything else, even though they works fine

**Comment by samuelrsilva** [comment]
Could you please elaborate on why using other programs is undesired?

Please remember that pdb2stl is a mere automation utility. All heavy work is done by EDTSurf, which does not deal with cartoon representation. Enabling it requires EDTSurf's replacement.

Alternatively, PyMol can create models in such representation, has the 'save' command to write them to VRML (https://pymolwiki.org/index.php/Surface#Exporting_Surface.2FMesh_Coordinates_to_File), and can be automated  (https://techoverflow.net/2018/03/13/automated-rendering-of-pdb-proteins-using-pymol).
My suggestion is to create the VRML model in PyMol and convert it to STL using, for example, https://github.com/djkonro/vrml-stl

**Comment by joaolaureano** [comment]
> Could you please elaborate on why using other programs is undesired?

Sure. My tool is designed to be used by impaired users. This way, obligating to use PyMol, Chimera, or any other stuff like that is not good, since they are pretty complex for this type of user. This way, I wanna make something easy as click in a button to elaborate a STL, then print in a 3D printer. It's a feature, not something really necessary, but it would be something awesome to do.

> My suggestion is to create the VRML model in PyMol and convert it to STL using, for example, https://github.com/djkonro/vrml-stl

Great, I gotta check it! My search about Pymol (chimera either, btw) did not result in something I wanted, but I haven't seen that.
